plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'net.minecraftforge.gradle' version '6.0.36' apply false
}

subprojects {
    version = mod_version
    group = mod_group_id
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.register("compileAllTargets") {
    group = "build"
    description = "Compiles all supported loader targets."

    dependsOn(
            ":targets:forge-1.20.1:compileJava",
            ":targets:neoforge-1.21.1:compileJava"
    )
}

tasks.register("processAllTargetResources") {
    group = "build"
    description = "Processes resources for all supported loader targets."

    dependsOn(
            ":targets:forge-1.20.1:processResources",
            ":targets:neoforge-1.21.1:processResources"
    )
}

tasks.register("buildAllTargets") {
    group = "build"
    description = "Builds all supported loader targets."

    dependsOn(
            ":targets:forge-1.20.1:build",
            ":targets:neoforge-1.21.1:build"
    )
}
