plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

allprojects {
    version = mod_version
    group = mod_group_id

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "NeoForge"
            url = uri("https://maven.neoforged.net/releases")
        }
        maven {
            name = "Curios"
            url = uri("https://maven.theillusivec4.top/")
        }
    }
}

subprojects {
    pluginManager.withPlugin("java") {
        java.toolchain.languageVersion = JavaLanguageVersion.of(21)
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
