package com.dreamingfish.gridinventory.common.network;

import com.dreamingfish.gridinventory.DFGridInventory;
import com.dreamingfish.gridinventory.protocol.GridMessageDirection;
import com.dreamingfish.gridinventory.protocol.GridMessageRegistry;
import com.dreamingfish.gridinventory.protocol.GridMessageType;
import net.minecraft.resources.ResourceLocation;

public final class GridMessages {
    public static final GridMessageRegistry REGISTRY = new GridMessageRegistry();

    private GridMessages() {
    }

    public static final GridMessageType<DropEquipmentStorageEntryMessage> DROP_EQUIPMENT_STORAGE_ENTRY = register("drop_equipment_storage_entry", GridMessageDirection.CLIENT_TO_SERVER, DropEquipmentStorageEntryMessage.class, DropEquipmentStorageEntryMessage::handle);
    public static final GridMessageType<CreativeInsertIntoCurioMessage> CREATIVE_INSERT_INTO_CURIO = register("creative_insert_into_curio", GridMessageDirection.CLIENT_TO_SERVER, CreativeInsertIntoCurioMessage.class, CreativeInsertIntoCurioMessage::handle);
    public static final GridMessageType<CreativeInsertIntoEquipmentStorageMessage> CREATIVE_INSERT_INTO_EQUIPMENT_STORAGE = register("creative_insert_into_equipment_storage", GridMessageDirection.CLIENT_TO_SERVER, CreativeInsertIntoEquipmentStorageMessage.class, CreativeInsertIntoEquipmentStorageMessage::handle);
    public static final GridMessageType<CreativeInsertIntoGridMessage> CREATIVE_INSERT_INTO_GRID = register("creative_insert_into_grid", GridMessageDirection.CLIENT_TO_SERVER, CreativeInsertIntoGridMessage.class, CreativeInsertIntoGridMessage::handle);
    public static final GridMessageType<CreativeInsertIntoNestedGridMessage> CREATIVE_INSERT_INTO_NESTED_GRID = register("creative_insert_into_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, CreativeInsertIntoNestedGridMessage.class, CreativeInsertIntoNestedGridMessage::handle);
    public static final GridMessageType<CreativeInsertIntoPlayerSlotMessage> CREATIVE_INSERT_INTO_PLAYER_SLOT = register("creative_insert_into_player_slot", GridMessageDirection.CLIENT_TO_SERVER, CreativeInsertIntoPlayerSlotMessage.class, CreativeInsertIntoPlayerSlotMessage::handle);
    public static final GridMessageType<CreativeInsertIntoSearchableContainerMessage> CREATIVE_INSERT_INTO_SEARCHABLE_CONTAINER = register("creative_insert_into_searchable_container", GridMessageDirection.CLIENT_TO_SERVER, CreativeInsertIntoSearchableContainerMessage.class, CreativeInsertIntoSearchableContainerMessage::handle);
    public static final GridMessageType<DropCurioMessage> DROP_CURIO = register("drop_curio", GridMessageDirection.CLIENT_TO_SERVER, DropCurioMessage.class, DropCurioMessage::handle);
    public static final GridMessageType<DropGridEntryMessage> DROP_GRID_ENTRY = register("drop_grid_entry", GridMessageDirection.CLIENT_TO_SERVER, DropGridEntryMessage.class, DropGridEntryMessage::handle);
    public static final GridMessageType<DropNestedGridEntryMessage> DROP_NESTED_GRID_ENTRY = register("drop_nested_grid_entry", GridMessageDirection.CLIENT_TO_SERVER, DropNestedGridEntryMessage.class, DropNestedGridEntryMessage::handle);
    public static final GridMessageType<DropPlayerSlotMessage> DROP_PLAYER_SLOT = register("drop_player_slot", GridMessageDirection.CLIENT_TO_SERVER, DropPlayerSlotMessage.class, DropPlayerSlotMessage::handle);
    public static final GridMessageType<ExtractCurioToEquipmentStorageMessage> EXTRACT_CURIO_TO_EQUIPMENT_STORAGE = register("extract_curio_to_equipment_storage", GridMessageDirection.CLIENT_TO_SERVER, ExtractCurioToEquipmentStorageMessage.class, ExtractCurioToEquipmentStorageMessage::handle);
    public static final GridMessageType<ExtractCurioToGridMessage> EXTRACT_CURIO_TO_GRID = register("extract_curio_to_grid", GridMessageDirection.CLIENT_TO_SERVER, ExtractCurioToGridMessage.class, ExtractCurioToGridMessage::handle);
    public static final GridMessageType<ExtractCurioToNestedGridMessage> EXTRACT_CURIO_TO_NESTED_GRID = register("extract_curio_to_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, ExtractCurioToNestedGridMessage.class, ExtractCurioToNestedGridMessage::handle);
    public static final GridMessageType<ExtractCurioToPlayerSlotMessage> EXTRACT_CURIO_TO_PLAYER_SLOT = register("extract_curio_to_player_slot", GridMessageDirection.CLIENT_TO_SERVER, ExtractCurioToPlayerSlotMessage.class, ExtractCurioToPlayerSlotMessage::handle);
    public static final GridMessageType<ExtractEquipmentStorageEntryMessage> EXTRACT_EQUIPMENT_STORAGE_ENTRY = register("extract_equipment_storage_entry", GridMessageDirection.CLIENT_TO_SERVER, ExtractEquipmentStorageEntryMessage.class, ExtractEquipmentStorageEntryMessage::handle);
    public static final GridMessageType<ExtractGridEntryToPlayerSlotMessage> EXTRACT_GRID_ENTRY_TO_PLAYER_SLOT = register("extract_grid_entry_to_player_slot", GridMessageDirection.CLIENT_TO_SERVER, ExtractGridEntryToPlayerSlotMessage.class, ExtractGridEntryToPlayerSlotMessage::handle);
    public static final GridMessageType<ExtractNestedGridEntryToPlayerSlotMessage> EXTRACT_NESTED_GRID_ENTRY_TO_PLAYER_SLOT = register("extract_nested_grid_entry_to_player_slot", GridMessageDirection.CLIENT_TO_SERVER, ExtractNestedGridEntryToPlayerSlotMessage.class, ExtractNestedGridEntryToPlayerSlotMessage::handle);
    public static final GridMessageType<ExtractToPlayerInventoryMessage> EXTRACT_TO_PLAYER_INVENTORY = register("extract_to_player_inventory", GridMessageDirection.CLIENT_TO_SERVER, ExtractToPlayerInventoryMessage.class, ExtractToPlayerInventoryMessage::handle);
    public static final GridMessageType<InsertEquipmentStorageEntryIntoCurioMessage> INSERT_EQUIPMENT_STORAGE_ENTRY_INTO_CURIO = register("insert_equipment_storage_entry_into_curio", GridMessageDirection.CLIENT_TO_SERVER, InsertEquipmentStorageEntryIntoCurioMessage.class, InsertEquipmentStorageEntryIntoCurioMessage::handle);
    public static final GridMessageType<InsertFromPlayerInventoryMessage> INSERT_FROM_PLAYER_INVENTORY = register("insert_from_player_inventory", GridMessageDirection.CLIENT_TO_SERVER, InsertFromPlayerInventoryMessage.class, InsertFromPlayerInventoryMessage::handle);
    public static final GridMessageType<InsertGridEntryIntoCurioMessage> INSERT_GRID_ENTRY_INTO_CURIO = register("insert_grid_entry_into_curio", GridMessageDirection.CLIENT_TO_SERVER, InsertGridEntryIntoCurioMessage.class, InsertGridEntryIntoCurioMessage::handle);
    public static final GridMessageType<InsertIntoEquipmentStorageMessage> INSERT_INTO_EQUIPMENT_STORAGE = register("insert_into_equipment_storage", GridMessageDirection.CLIENT_TO_SERVER, InsertIntoEquipmentStorageMessage.class, InsertIntoEquipmentStorageMessage::handle);
    public static final GridMessageType<InsertPlayerSlotIntoNestedGridMessage> INSERT_PLAYER_SLOT_INTO_NESTED_GRID = register("insert_player_slot_into_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, InsertPlayerSlotIntoNestedGridMessage.class, InsertPlayerSlotIntoNestedGridMessage::handle);
    public static final GridMessageType<InsertPlayerSlotIntoCurioMessage> INSERT_PLAYER_SLOT_INTO_CURIO = register("insert_player_slot_into_curio", GridMessageDirection.CLIENT_TO_SERVER, InsertPlayerSlotIntoCurioMessage.class, InsertPlayerSlotIntoCurioMessage::handle);
    public static final GridMessageType<ManualPickupItemMessage> MANUAL_PICKUP_ITEM = register("manual_pickup_item", GridMessageDirection.CLIENT_TO_SERVER, ManualPickupItemMessage.class, ManualPickupItemMessage::handle);
    public static final GridMessageType<MoveEquipmentStorageEntryMessage> MOVE_EQUIPMENT_STORAGE_ENTRY = register("move_equipment_storage_entry", GridMessageDirection.CLIENT_TO_SERVER, MoveEquipmentStorageEntryMessage.class, MoveEquipmentStorageEntryMessage::handle);
    public static final GridMessageType<MoveGridEntryMessage> MOVE_GRID_ENTRY = register("move_grid_entry", GridMessageDirection.CLIENT_TO_SERVER, MoveGridEntryMessage.class, MoveGridEntryMessage::handle);
    public static final GridMessageType<MoveItemMessage> MOVE_ITEM = register("move_item", GridMessageDirection.CLIENT_TO_SERVER, MoveItemMessage.class, MoveItemMessage::handle);
    public static final GridMessageType<MovePlayerFreeSlotMessage> MOVE_PLAYER_FREE_SLOT = register("move_player_free_slot", GridMessageDirection.CLIENT_TO_SERVER, MovePlayerFreeSlotMessage.class, MovePlayerFreeSlotMessage::handle);
    public static final GridMessageType<MovePlayerSlotToSearchableContainerMessage> MOVE_PLAYER_SLOT_TO_SEARCHABLE_CONTAINER = register("move_player_slot_to_searchable_container", GridMessageDirection.CLIENT_TO_SERVER, MovePlayerSlotToSearchableContainerMessage.class, MovePlayerSlotToSearchableContainerMessage::handle);
    public static final GridMessageType<MoveSearchableContainerEntryMessage> MOVE_SEARCHABLE_CONTAINER_ENTRY = register("move_searchable_container_entry", GridMessageDirection.CLIENT_TO_SERVER, MoveSearchableContainerEntryMessage.class, MoveSearchableContainerEntryMessage::handle);
    public static final GridMessageType<MoveSearchableContainerEntryToPlayerSlotMessage> MOVE_SEARCHABLE_CONTAINER_ENTRY_TO_PLAYER_SLOT = register("move_searchable_container_entry_to_player_slot", GridMessageDirection.CLIENT_TO_SERVER, MoveSearchableContainerEntryToPlayerSlotMessage.class, MoveSearchableContainerEntryToPlayerSlotMessage::handle);
    public static final GridMessageType<OpenPlayerGridInventoryMessage> OPEN_PLAYER_GRID_INVENTORY = register("open_player_grid_inventory", GridMessageDirection.CLIENT_TO_SERVER, OpenPlayerGridInventoryMessage.class, OpenPlayerGridInventoryMessage::handle);
    public static final GridMessageType<RequestExternalPlayerGridMessage> REQUEST_EXTERNAL_PLAYER_GRID = register("request_external_player_grid", GridMessageDirection.CLIENT_TO_SERVER, RequestExternalPlayerGridMessage.class, RequestExternalPlayerGridMessage::handle);
    public static final GridMessageType<PickupGroundItemIntoEquipmentStorageMessage> PICKUP_GROUND_ITEM_INTO_EQUIPMENT_STORAGE = register("pickup_ground_item_into_equipment_storage", GridMessageDirection.CLIENT_TO_SERVER, PickupGroundItemIntoEquipmentStorageMessage.class, PickupGroundItemIntoEquipmentStorageMessage::handle);
    public static final GridMessageType<PickupGroundItemIntoCurioMessage> PICKUP_GROUND_ITEM_INTO_CURIO = register("pickup_ground_item_into_curio", GridMessageDirection.CLIENT_TO_SERVER, PickupGroundItemIntoCurioMessage.class, PickupGroundItemIntoCurioMessage::handle);
    public static final GridMessageType<PickupGroundItemIntoGridMessage> PICKUP_GROUND_ITEM_INTO_GRID = register("pickup_ground_item_into_grid", GridMessageDirection.CLIENT_TO_SERVER, PickupGroundItemIntoGridMessage.class, PickupGroundItemIntoGridMessage::handle);
    public static final GridMessageType<PickupGroundItemIntoNestedGridMessage> PICKUP_GROUND_ITEM_INTO_NESTED_GRID = register("pickup_ground_item_into_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, PickupGroundItemIntoNestedGridMessage.class, PickupGroundItemIntoNestedGridMessage::handle);
    public static final GridMessageType<PickupGroundItemIntoPlayerSlotMessage> PICKUP_GROUND_ITEM_INTO_PLAYER_SLOT = register("pickup_ground_item_into_player_slot", GridMessageDirection.CLIENT_TO_SERVER, PickupGroundItemIntoPlayerSlotMessage.class, PickupGroundItemIntoPlayerSlotMessage::handle);
    public static final GridMessageType<PickupGroundItemIntoSearchableContainerMessage> PICKUP_GROUND_ITEM_INTO_SEARCHABLE_CONTAINER = register("pickup_ground_item_into_searchable_container", GridMessageDirection.CLIENT_TO_SERVER, PickupGroundItemIntoSearchableContainerMessage.class, PickupGroundItemIntoSearchableContainerMessage::handle);
    public static final GridMessageType<QuickEquipEquipmentStorageEntryMessage> QUICK_EQUIP_EQUIPMENT_STORAGE_ENTRY = register("quick_equip_equipment_storage_entry", GridMessageDirection.CLIENT_TO_SERVER, QuickEquipEquipmentStorageEntryMessage.class, QuickEquipEquipmentStorageEntryMessage::handle);
    public static final GridMessageType<QuickEquipGridEntryMessage> QUICK_EQUIP_GRID_ENTRY = register("quick_equip_grid_entry", GridMessageDirection.CLIENT_TO_SERVER, QuickEquipGridEntryMessage.class, QuickEquipGridEntryMessage::handle);
    public static final GridMessageType<QuickEquipNestedGridEntryMessage> QUICK_EQUIP_NESTED_GRID_ENTRY = register("quick_equip_nested_grid_entry", GridMessageDirection.CLIENT_TO_SERVER, QuickEquipNestedGridEntryMessage.class, QuickEquipNestedGridEntryMessage::handle);
    public static final GridMessageType<QuickEquipPlayerSlotMessage> QUICK_EQUIP_PLAYER_SLOT = register("quick_equip_player_slot", GridMessageDirection.CLIENT_TO_SERVER, QuickEquipPlayerSlotMessage.class, QuickEquipPlayerSlotMessage::handle);
    public static final GridMessageType<SyncBackpackFoldingRulesMessage> SYNC_BACKPACK_FOLDING_RULES = register("sync_backpack_folding_rules", GridMessageDirection.SERVER_TO_CLIENT, SyncBackpackFoldingRulesMessage.class, SyncBackpackFoldingRulesMessage::handle);
    public static final GridMessageType<SyncEquipmentStorageMessage> SYNC_EQUIPMENT_STORAGE = register("sync_equipment_storage", GridMessageDirection.SERVER_TO_CLIENT, SyncEquipmentStorageMessage.class, SyncEquipmentStorageMessage::handle);
    public static final GridMessageType<SyncExternalPlayerGridMessage> SYNC_EXTERNAL_PLAYER_GRID = register("sync_external_player_grid", GridMessageDirection.SERVER_TO_CLIENT, SyncExternalPlayerGridMessage.class, SyncExternalPlayerGridMessage::handle);
    public static final GridMessageType<SyncGridInventoryMessage> SYNC_GRID_INVENTORY = register("sync_grid_inventory", GridMessageDirection.SERVER_TO_CLIENT, SyncGridInventoryMessage.class, SyncGridInventoryMessage::handle);
    public static final GridMessageType<SyncItemSizeRulesMessage> SYNC_ITEM_SIZE_RULES = register("sync_item_size_rules", GridMessageDirection.SERVER_TO_CLIENT, SyncItemSizeRulesMessage.class, SyncItemSizeRulesMessage::handle);
    public static final GridMessageType<SyncSearchableContainerGridMessage> SYNC_SEARCHABLE_CONTAINER_GRID = register("sync_searchable_container_grid", GridMessageDirection.SERVER_TO_CLIENT, SyncSearchableContainerGridMessage.class, SyncSearchableContainerGridMessage::handle);
    public static final GridMessageType<ToggleEquipmentStorageEntryBackpackFoldMessage> TOGGLE_EQUIPMENT_STORAGE_ENTRY_BACKPACK_FOLD = register("toggle_equipment_storage_entry_backpack_fold", GridMessageDirection.CLIENT_TO_SERVER, ToggleEquipmentStorageEntryBackpackFoldMessage.class, ToggleEquipmentStorageEntryBackpackFoldMessage::handle);
    public static final GridMessageType<ToggleGridEntryBackpackFoldMessage> TOGGLE_GRID_ENTRY_BACKPACK_FOLD = register("toggle_grid_entry_backpack_fold", GridMessageDirection.CLIENT_TO_SERVER, ToggleGridEntryBackpackFoldMessage.class, ToggleGridEntryBackpackFoldMessage::handle);
    public static final GridMessageType<TransferEquipmentStorageEntryIntoGridMessage> TRANSFER_EQUIPMENT_STORAGE_ENTRY_INTO_GRID = register("transfer_equipment_storage_entry_into_grid", GridMessageDirection.CLIENT_TO_SERVER, TransferEquipmentStorageEntryIntoGridMessage.class, TransferEquipmentStorageEntryIntoGridMessage::handle);
    public static final GridMessageType<TransferEquipmentStorageEntryIntoNestedGridMessage> TRANSFER_EQUIPMENT_STORAGE_ENTRY_INTO_NESTED_GRID = register("transfer_equipment_storage_entry_into_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, TransferEquipmentStorageEntryIntoNestedGridMessage.class, TransferEquipmentStorageEntryIntoNestedGridMessage::handle);
    public static final GridMessageType<TransferEquipmentStorageEntryMessage> TRANSFER_EQUIPMENT_STORAGE_ENTRY = register("transfer_equipment_storage_entry", GridMessageDirection.CLIENT_TO_SERVER, TransferEquipmentStorageEntryMessage.class, TransferEquipmentStorageEntryMessage::handle);
    public static final GridMessageType<TransferGridEntryIntoEquipmentStorageMessage> TRANSFER_GRID_ENTRY_INTO_EQUIPMENT_STORAGE = register("transfer_grid_entry_into_equipment_storage", GridMessageDirection.CLIENT_TO_SERVER, TransferGridEntryIntoEquipmentStorageMessage.class, TransferGridEntryIntoEquipmentStorageMessage::handle);
    public static final GridMessageType<TransferGridEntryIntoNestedGridMessage> TRANSFER_GRID_ENTRY_INTO_NESTED_GRID = register("transfer_grid_entry_into_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, TransferGridEntryIntoNestedGridMessage.class, TransferGridEntryIntoNestedGridMessage::handle);
    public static final GridMessageType<TransferNestedGridEntryIntoEquipmentStorageMessage> TRANSFER_NESTED_GRID_ENTRY_INTO_EQUIPMENT_STORAGE = register("transfer_nested_grid_entry_into_equipment_storage", GridMessageDirection.CLIENT_TO_SERVER, TransferNestedGridEntryIntoEquipmentStorageMessage.class, TransferNestedGridEntryIntoEquipmentStorageMessage::handle);
    public static final GridMessageType<TransferNestedGridEntryIntoGridMessage> TRANSFER_NESTED_GRID_ENTRY_INTO_GRID = register("transfer_nested_grid_entry_into_grid", GridMessageDirection.CLIENT_TO_SERVER, TransferNestedGridEntryIntoGridMessage.class, TransferNestedGridEntryIntoGridMessage::handle);
    public static final GridMessageType<TransferNestedGridEntryIntoNestedGridMessage> TRANSFER_NESTED_GRID_ENTRY_INTO_NESTED_GRID = register("transfer_nested_grid_entry_into_nested_grid", GridMessageDirection.CLIENT_TO_SERVER, TransferNestedGridEntryIntoNestedGridMessage.class, TransferNestedGridEntryIntoNestedGridMessage::handle);
    public static final GridMessageType<CreativeDiscardItemMessage> CREATIVE_DISCARD_ITEM = register("creative_discard_item", GridMessageDirection.CLIENT_TO_SERVER, CreativeDiscardItemMessage.class, CreativeDiscardItemMessage::handle);

    private static <T extends com.dreamingfish.gridinventory.protocol.GridMessage> GridMessageType<T> register(String path, GridMessageDirection direction, Class<T> messageClass, com.dreamingfish.gridinventory.protocol.GridMessageHandler<T> handler) {
        return REGISTRY.register(new GridMessageType<>(ResourceLocation.fromNamespaceAndPath(DFGridInventory.MODID, path), direction, messageClass, handler));
    }
}
