plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_id}-neoforge-1.21.1"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
    maven {
        name = "CurseMaven"
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets {
    main {
        java.srcDir rootProject.file("common/src/main/java")
        resources.srcDir rootProject.file("common/src/main/resources")
        resources.srcDir "src/generated/resources"
    }
}

configurations {
    localRuntime
    runtimeClasspath.extendsFrom localRuntime
}

def rarityCoreNeoForge1211 =
        "curse.maven:raritycore-1441762:${raritycore_neoforge_1211_file_id}"

def enableRarityCoreRuntime =
        (findProperty("raritycore_runtime") ?: "false").toBoolean()

dependencies {
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1"
    compileOnly "top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1:api"
    // 仅开发运行时加载
    if (enableRarityCoreRuntime) {
        localRuntime rarityCoreNeoForge1211
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
