plugins {
    id 'java-library'
    id 'net.minecraftforge.gradle'
}

base {
    archivesName = "${mod_id}-forge-1.20.1"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: project.forge_1201_minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            args '--mixin.config=df_grid_inventory.forge1201.mixins.json'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            args '--nogui'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets {
    main {
        java.setSrcDirs([file("src/main/java"), rootProject.project(":common").file("src/main/java")])
        java.exclude { details ->
            def commonSource = rootProject.project(":common").file("src/main/java").toPath()
            def filePath = details.file.toPath()
            if (!filePath.startsWith(commonSource)) {
                return false
            }
            return details.path == "com/dreamingfish/gridinventory/common/item/SmallGridBagItem.java"
        }
        resources.srcDir rootProject.project(":common").file("src/main/resources")
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${forge_1201_minecraft_version}-${forge_1201_version}"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version_range: forge_1201_minecraft_version_range,
            loader_version_range   : forge_1201_loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/mods.toml') {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'MixinConfigs': 'df_grid_inventory.forge1201.mixins.json'
        ])
    }
}
